services:
  - type: web
    name: realtime-room-api
    runtime: docker
    plan: free
    repo: https://github.com/Lafuente-Nicolas/RealTime-Room
    branch: main
    dockerContext: app/api
    dockerfilePath: Dockerfile
    healthCheckPath: /health
    autoDeploy: true
